export const COUNTRIES = [
  { name: "Afghanistan", code: "+93" },
  { name: "Albanie", code: "+355" },
  { name: "Algérie", code: "+213" },
  { name: "Andorre", code: "+376" },
  { name: "Angola", code: "+244" },
  { name: "Antigua-et-Barbuda", code: "+1-268" },
  { name: "Argentine", code: "+54" },
  { name: "Arménie", code: "+374" },
  { name: "Australie", code: "+61" },
  { name: "Autriche", code: "+43" },
  { name: "Azerbaïdjan", code: "+994" },
  { name: "Bahamas", code: "+1-242" },
  { name: "Bahreïn", code: "+973" },
  { name: "Bangladesh", code: "+880" },
  { name: "Barbade", code: "+1-246" },
  { name: "Bélarus", code: "+375" },
  { name: "Belgique", code: "+32" },
  { name: "Belize", code: "+501" },
  { name: "Bénin", code: "+229" },
  { name: "Bhoutan", code: "+975" },
  { name: "Bolivie", code: "+591" },
  { name: "Bosnie-Herzégovine", code: "+387" },
  { name: "Botswana", code: "+267" },
  { name: "Brésil", code: "+55" },
  { name: "Brunéi Darussalam", code: "+673" },
  { name: "Bulgarie", code: "+359" },
  { name: "Burkina Faso", code: "+226" },
  { name: "Burundi", code: "+257" },
  { name: "Cabo Verde", code: "+238" },
  { name: "Cambodge", code: "+855" },
  { name: "Cameroun", code: "+237" },
  { name: "Canada", code: "+1" },
  { name: "République centrafricaine", code: "+236" },
  { name: "Tchad", code: "+235" },
  { name: "Chili", code: "+56" },
  { name: "Chine", code: "+86" },
  { name: "Colombie", code: "+57" },
  { name: "Comores", code: "+269" },
  { name: "Congo", code: "+242" },
  { name: "République démocratique du Congo", code: "+243" },
  { name: "Costa Rica", code: "+506" },
  { name: "Côte d'Ivoire", code: "+225" },
  { name: "Croatie", code: "+385" },
  { name: "Cuba", code: "+53" },
  { name: "Chypre", code: "+357" },
  { name: "Tchéquie", code: "+420" },
  { name: "Danemark", code: "+45" },
  { name: "Djibouti", code: "+253" },
  { name: "Dominique", code: "+1-767" },
  { name: "République dominicaine", code: "+1-809" },
  { name: "Équateur", code: "+593" },
  { name: "Égypte", code: "+20" },
  { name: "El Salvador", code: "+503" },
  { name: "Guinée équatoriale", code: "+240" },
  { name: "Érythrée", code: "+291" },
  { name: "Estonie", code: "+372" },
  { name: "Eswatini", code: "+268" },
  { name: "Éthiopie", code: "+251" },
  { name: "Fidji", code: "+679" },
  { name: "Finlande", code: "+358" },
  { name: "France", code: "+33" },
  { name: "Gabon", code: "+241" },
  { name: "Gambie", code: "+220" },
  { name: "Géorgie", code: "+995" },
  { name: "Allemagne", code: "+49" },
  { name: "Ghana", code: "+233" },
  { name: "Grèce", code: "+30" },
  { name: "Grenade", code: "+1-473" },
  { name: "Guatemala", code: "+502" },
  { name: "Guinée", code: "+224" },
  { name: "Guinée-Bissau", code: "+245" },
  { name: "Guyana", code: "+592" },
  { name: "Haïti", code: "+509" },
  { name: "Honduras", code: "+504" },
  { name: "Hongrie", code: "+36" },
  { name: "Islande", code: "+354" },
  { name: "Inde", code: "+91" },
  { name: "Indonésie", code: "+62" },
  { name: "Iran", code: "+98" },
  { name: "Iraq", code: "+964" },
  { name: "Irlande", code: "+353" },
  { name: "Israël", code: "+972" },
  { name: "Italie", code: "+39" },
  { name: "Jamaïque", code: "+1-876" },
  { name: "Japon", code: "+81" },
  { name: "Jordanie", code: "+962" },
  { name: "Kazakhstan", code: "+7" },
  { name: "Kenya", code: "+254" },
  { name: "Kiribati", code: "+686" },
  { name: "Koweït", code: "+965" },
  { name: "Kirghizistan", code: "+996" },
  { name: "Laos", code: "+856" },
  { name: "Lettonie", code: "+371" },
  { name: "Liban", code: "+961" },
  { name: "Lesotho", code: "+266" },
  { name: "Libéria", code: "+231" },
  { name: "Libye", code: "+218" },
  { name: "Liechtenstein", code: "+423" },
  { name: "Lituanie", code: "+370" },
  { name: "Luxembourg", code: "+352" },
  { name: "Madagascar", code: "+261" },
  { name: "Malawi", code: "+265" },
  { name: "Malaisie", code: "+60" },
  { name: "Maldives", code: "+960" },
  { name: "Mali", code: "+223" },
  { name: "Malte", code: "+356" },
  { name: "Îles Marshall", code: "+692" },
  { name: "Mauritanie", code: "+222" },
  { name: "Maurice", code: "+230" },
  { name: "Mexique", code: "+52" },
  { name: "Micronésie", code: "+691" },
  { name: "Monaco", code: "+377" },
  { name: "Mongolie", code: "+976" },
  { name: "Monténégro", code: "+382" },
  { name: "Maroc", code: "+212" },
  { name: "Mozambique", code: "+258" },
  { name: "Myanmar", code: "+95" },
  { name: "Namibie", code: "+264" },
  { name: "Nauru", code: "+674" },
  { name: "Népal", code: "+977" },
  { name: "Pays-Bas", code: "+31" },
  { name: "Nouvelle-Zélande", code: "+64" },
  { name: "Nicaragua", code: "+505" },
  { name: "Niger", code: "+227" },
  { name: "Nigéria", code: "+234" },
  { name: "Corée du Nord", code: "+850" },
  { name: "Macédoine du Nord", code: "+389" },
  { name: "Norvège", code: "+47" },
  { name: "Oman", code: "+968" },
  { name: "Pakistan", code: "+92" },
  { name: "Palaos", code: "+680" },
  { name: "Palestine", code: "+970" },
  { name: "Panama", code: "+507" },
  { name: "Papouasie-Nouvelle-Guinée", code: "+675" },
  { name: "Paraguay", code: "+595" },
  { name: "Pérou", code: "+51" },
  { name: "Philippines", code: "+63" },
  { name: "Pologne", code: "+48" },
  { name: "Portugal", code: "+351" },
  { name: "Qatar", code: "+974" },
  { name: "Corée du Sud", code: "+82" },
  { name: "Moldavie", code: "+373" },
  { name: "Roumanie", code: "+40" },
  { name: "Russie", code: "+7" },
  { name: "Rwanda", code: "+250" },
  { name: "Saint-Kitts-et-Nevis", code: "+1-869" },
  { name: "Sainte-Lucie", code: "+1-758" },
  { name: "Saint-Vincent-et-les-Grenadines", code: "+1-784" },
  { name: "Samoa", code: "+685" },
  { name: "Saint-Marin", code: "+378" },
  { name: "Sao Tomé-et-Principe", code: "+239" },
  { name: "Arabie saoudite", code: "+966" },
  { name: "Sénégal", code: "+221" },
  { name: "Serbie", code: "+381" },
  { name: "Seychelles", code: "+248" },
  { name: "Sierra Leone", code: "+232" },
  { name: "Singapour", code: "+65" },
  { name: "Slovaquie", code: "+421" },
  { name: "Slovénie", code: "+386" },
  { name: "Îles Salomon", code: "+677" },
  { name: "Somalie", code: "+252" },
  { name: "Afrique du Sud", code: "+27" },
  { name: "Soudan du Sud", code: "+211" },
  { name: "Espagne", code: "+34" },
  { name: "Sri Lanka", code: "+94" },
  { name: "Soudan", code: "+249" },
  { name: "Suriname", code: "+597" },
  { name: "Suède", code: "+46" },
  { name: "Suisse", code: "+41" },
  { name: "Syrie", code: "+963" },
  { name: "Tadjikistan", code: "+992" },
  { name: "Tanzanie", code: "+255" },
  { name: "Thaïlande", code: "+66" },
  { name: "Timor-Leste", code: "+670" },
  { name: "Togo", code: "+228" },
  { name: "Tonga", code: "+676" },
  { name: "Trinité-et-Tobago", code: "+1-868" },
  { name: "Tunisie", code: "+216" },
  { name: "Turquie", code: "+90" },
  { name: "Turkménistan", code: "+993" },
  { name: "Tuvalu", code: "+688" },
  { name: "Ouganda", code: "+256" },
  { name: "Ukraine", code: "+380" },
  { name: "Émirats arabes unis", code: "+971" },
  { name: "Royaume-Uni", code: "+44" },
  { name: "États-Unis", code: "+1" },
  { name: "Uruguay", code: "+598" },
  { name: "Ouzbékistan", code: "+998" },
  { name: "Vanuatu", code: "+678" },
  { name: "Venezuela", code: "+58" },
  { name: "Viêt Nam", code: "+84" },
  { name: "Yémen", code: "+967" },
  { name: "Zambie", code: "+260" },
  { name: "Zimbabwe", code: "+263" }
] as const;

export const COUNTRY_NAMES = COUNTRIES.map(c => c.name).sort((a, b) => a.localeCompare(b, "fr"));
export const CALLING_CODES = Array.from(new Set(COUNTRIES.map(c => c.code))).sort((a, b) => {
  const codeA = parseInt(a.replace(/\D/g, ""));
  const codeB = parseInt(b.replace(/\D/g, ""));
  return codeA - codeB;
});
