-- Limitation distribuée des requêtes de l'API publique du widget.
-- Aucun identifiant IP brut n'est stocké : l'API transmet une empreinte HMAC.

create table public.widget_rate_limits (
  id bigint generated by default as identity primary key,
  request_fingerprint text not null,
  scope text not null,
  window_started_at timestamptz not null,
  request_count integer not null default 1,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint widget_rate_limits_window_key
    unique (request_fingerprint, scope, window_started_at),
  constraint widget_rate_limits_count_positive check (request_count > 0),
  constraint widget_rate_limits_fingerprint_length check (
    char_length(request_fingerprint) between 32 and 128
  ),
  constraint widget_rate_limits_scope_length check (
    char_length(scope) between 3 and 180
  )
);

create index idx_widget_rate_limits_expiry
  on public.widget_rate_limits (expires_at);

alter table public.widget_rate_limits enable row level security;
revoke all on table public.widget_rate_limits from anon, authenticated;
revoke all on sequence public.widget_rate_limits_id_seq from anon, authenticated;

create policy "widget_rate_limits_deny_anon"
  on public.widget_rate_limits for all to anon
  using (false) with check (false);

create policy "widget_rate_limits_deny_authenticated"
  on public.widget_rate_limits for all to authenticated
  using (false) with check (false);

grant all on table public.widget_rate_limits to service_role;
grant usage, select on sequence public.widget_rate_limits_id_seq to service_role;

create trigger trg_widget_rate_limits_touch
  before update on public.widget_rate_limits
  for each row execute function public.touch_updated_at();

create or replace function public.consume_widget_rate_limit(
  p_request_fingerprint text,
  p_scope text,
  p_limit integer,
  p_window_seconds integer
)
returns boolean
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_window_started_at timestamptz;
  v_request_count integer;
begin
  if char_length(coalesce(p_request_fingerprint, '')) not between 32 and 128
    or char_length(coalesce(p_scope, '')) not between 3 and 180
    or p_limit < 1
    or p_window_seconds < 1
    or p_window_seconds > 86400
  then
    raise exception 'Invalid rate limit parameters.';
  end if;

  v_window_started_at := to_timestamp(
    floor(extract(epoch from clock_timestamp()) / p_window_seconds) * p_window_seconds
  );

  insert into public.widget_rate_limits (
    request_fingerprint,
    scope,
    window_started_at,
    request_count,
    expires_at
  ) values (
    p_request_fingerprint,
    p_scope,
    v_window_started_at,
    1,
    v_window_started_at + make_interval(secs => p_window_seconds * 2)
  )
  on conflict (request_fingerprint, scope, window_started_at)
  do update set
    request_count = widget_rate_limits.request_count + 1,
    expires_at = excluded.expires_at
  returning request_count into v_request_count;

  return v_request_count <= p_limit;
end;
$$;

revoke all on function public.consume_widget_rate_limit(text, text, integer, integer) from public;
grant execute on function public.consume_widget_rate_limit(text, text, integer, integer) to service_role;

comment on function public.consume_widget_rate_limit(text, text, integer, integer) is
  'Limiteur atomique réservé au service_role. Retourne false lorsque la fenêtre est dépassée.';

-- Bucket privé : seuls les jetons d'upload signés par l'API serveur permettent
-- un envoi. Aucune policy anon de lecture ou d'écriture n'est créée.
insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
) values (
  'widget-uploads',
  'widget-uploads',
  false,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif']
)
on conflict (id) do update set
  public = false,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
